locallibrary/catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

locallibrary/locallibrary/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
    url(r'^accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
import uuid

# Create your models here. 
class Genre(models.Model):
    """
        Model resprenting the book genre
    """
    name=models.CharField(max_length=200, help_text="Enter a book genre")
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description")
    isbn = models.CharField('ISBN', max_length=13, help_text="13 character ISBN field")
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3] ])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique book number")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
            ('d', 'Maintenance'),
            ('o', 'On loan'),
            ('a', 'Available'),
            ('r', 'Reserved'),
        )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='d', help_text="Book Availability")

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return ('%s (%s)' %(self.id, self.book.title))

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.CharField(max_length=10, null=True, blank=True)
    date_of_death = models.CharField(max_length=10, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    def __str__(self):
        return ('%s, %s' % (self.last_name, self.first_name))

    def display_books(self):
        books = Book.objects.get(pk=self.id)
        return books.book_set.all()

    display_books.short_description = 'Books'

locallibrary/catalog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic

# Create your views here.

from .models import Book, Author, BookInstance, Genre

def index(request):
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    #available books
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()

    #number of visits to this view as in session var
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    return render(request, 
        'index.html', 
        context={'num_books': num_books, 'num_instances': num_instances, 
            'num_instances_available' : num_instances_available, 'num_authors': num_authors, 'num_visits': num_visits},
    )

class BookListView(generic.ListView):
   model = Book

class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

locallibrary/catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}<title>Local Library</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static "css/styles.css" %}">
    </head>

    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %} 
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'books' %}">All books</a></li>
                        <li><a href="{% url 'authors' %}">All authors</a></li>
                        {% if user.is_authenticated %}
                            <li>User: {{ user.get_username }}</li>
                            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                        {% endif %}
                    </ul>
                    {% endblock %}
                </div>
            </div>
            <div class="col-sm-10 ">
            {% block content %}{% endblock %}
            </div>
        </div>
    </body>
</html>

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Author: {{ author }}</h1>
  <p><strong>Date of Birth:</strong> {{ author.date_of_birth }}</p>  
  <p><strong>Date of Death:</strong> {{ author.date_of_death }}</p>  
  <!--<p><strong>Books:</strong> {% for books in book.author.pk.all %} {{ book.author }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  -->


  <div style="margin-left:20px;margin-top:20px">
   <h4>Books</h4>
   {% for book in object.book_set.all %}
   <p>{{ book.title }} </p>
   {% endfor %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Author List</h1>

    {% if author_list %}
    <ul>
        {% for author in author_list %}
        <li>
            <a href="{{ author.get_absolute_url }}">{{ author.last_name }} , {{ author.first_name}}</a>
        </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Title: {{ book.title}} </h1>
  <p><strong>Author:</strong> {{ book.author }}</p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
        </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Local Library Home</h1>

<p>Welcome to <em>LocalLibrary</em>, a very basic Django website</p>

<h2>Dynamic Content</h2>

<p>The library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong>{{ num_books }}</li>
    <li><strong>Copies:</strong>{{ num_instances }}</li>
    <li><strong>Copies Available:</strong>{{ num_instances_available }}</li>
    <li><strong>Authors:</strong>{{ num_authors }}</li>
</ul>

<p>You have visisted this page {{ num_visits }} {% if num_visits == 1 %} time {% else %} times{% endif %}.</p>

{% endblock %}